/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.analizador.lexico.frontend;

import com.mycompany.analizador.lexico.backend.ArchivoEntrada;
import com.mycompany.analizador.lexico.backend.Lexer;
import com.mycompany.analizador.lexico.backend.Token;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.*;

/**
 *
 * @author mynordma
 */
public class FramePrincipal extends javax.swing.JFrame {
    private int filas;
    private int columnas;
    private List<String> colores;
    private List<String[]> parametrosEspeciales;
    private List<int[]> matriz;
    List<Token> tokens;
    private ArrayList<String[]> datosReporte;
    private ArrayList<CuadroPanel> casillas;

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        this.setTitle("Analizador Lexico");
        this.setSize(1000, 600);
        this.setLocationRelativeTo(null);
        this.generarBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        generarBtn = new javax.swing.JButton();
        cuadriculaPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        importarBtn = new javax.swing.JMenu();
        dimensionesBtn = new javax.swing.JMenu();
        reporteBtn = new javax.swing.JMenu();
        exportarBtn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        generarBtn.setText("Generar imagen");
        generarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarBtnActionPerformed(evt);
            }
        });

        cuadriculaPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout cuadriculaPanelLayout = new javax.swing.GroupLayout(cuadriculaPanel);
        cuadriculaPanel.setLayout(cuadriculaPanelLayout);
        cuadriculaPanelLayout.setHorizontalGroup(
            cuadriculaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        cuadriculaPanelLayout.setVerticalGroup(
            cuadriculaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));

        importarBtn.setText("Importar texto");
        importarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importarBtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(importarBtn);

        dimensionesBtn.setText("Establecer dimensiones de cuadricula");
        dimensionesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dimensionesBtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(dimensionesBtn);

        reporteBtn.setText("Reporte");
        reporteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reporteBtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(reporteBtn);

        exportarBtn.setText("Exportar PNG");
        exportarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exportarBtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(exportarBtn);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(generarBtn)
                        .addGap(184, 184, 184)))
                .addComponent(cuadriculaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generarBtn))
                    .addComponent(cuadriculaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importarBtnMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            ArchivoEntrada archivo = new ArchivoEntrada();
            archivo.leerContenido(fileChooser, textArea);
        }
    }//GEN-LAST:event_importarBtnMouseClicked

    private void generarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarBtnActionPerformed
        datosReporte = new ArrayList<>();
        casillas = new ArrayList<>();
        matriz = new ArrayList<>();

        // Separar cada palabra en el textArea
        ArchivoEntrada archivo = new ArchivoEntrada();
        String[] palabras = archivo.separarTokens(textArea.getText().trim());
        
        // Generar los tokens iterando por cada palabra y guardar los parametros de las funciones Square.Color
        tokens = new ArrayList<>();
        colores = new ArrayList<>();
        parametrosEspeciales = new ArrayList<>();
        List<String> coloresSquare2 = new ArrayList<>();
        
        for (String palabra : palabras) {
            Lexer lexer = new Lexer();
            System.out.println("Palabra: " + palabra);
            try {
               tokens.add(lexer.generarToken(palabra)); 
               if(lexer.getColorParametro() != null){
                    if(lexer.getFilaParametro() == null){
                        coloresSquare2.add(lexer.getColorParametro());
                    }
               }
               if(tokens.get(tokens.size()-1).getTipo().name().equals("SQUARE2")){
                   colores.add(coloresSquare2.get(coloresSquare2.size()-1));
               }else if(!tokens.get(tokens.size()-1).getTipo().name().equals("SQUARE1")){
                   colores.add(tokens.get(tokens.size()-1).getTipo().getColor());
               }else if(tokens.get(tokens.size()-1).getTipo().name().equals("SQUARE1")){
                   parametrosEspeciales.add(new String[]{lexer.getColorParametro(), lexer.getFilaParametro(), lexer.getColumnaParametro()});
               }
            } catch (RuntimeException e) {
                System.out.println(e.getMessage());
            }
            
            if(!tokens.isEmpty()){
                System.out.println("Token " + tokens.size() + ": " + tokens.get(tokens.size()-1).getTipo().name()); 
                
            }
            
        }
        
        // Asignar una fila y columna del editor a cada token
        asignarFilasYColumnas(archivo.getCantidadPalabrasEnLineas());
        
        // Pintar la cuadricula a partir de los colores guardados
        for (int i = 0; i < colores.size(); i++) {
            System.out.println("Color: " + colores.get(i));
            
        }
        pintarCuadricula();
        
    }//GEN-LAST:event_generarBtnActionPerformed

    private void dimensionesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dimensionesBtnMouseClicked
        // Crear el JDialog
        JDialog dialogo = new JDialog(this, "Establecer dimensiones", true);
        dialogo.setSize(300, 150);
        dialogo.setLocationRelativeTo(this);
        dialogo.setLayout(new java.awt.GridLayout(3, 2));

        // Etiquetas y campos de texto para filas y columnas
        javax.swing.JLabel filasLabel = new javax.swing.JLabel("Filas:");
        javax.swing.JTextField filasField = new javax.swing.JTextField();
        javax.swing.JLabel columnasLabel = new javax.swing.JLabel("Columnas:");
        javax.swing.JTextField columnasField = new javax.swing.JTextField();

        // Botón de confirmación
        javax.swing.JButton confirmarBtn = new javax.swing.JButton("Confirmar");
        confirmarBtn.addActionListener((java.awt.event.ActionEvent evt1) -> {
            try {
                int filasIngresadas = Integer.parseInt(filasField.getText().trim());
                int columnasIngresadas = Integer.parseInt(columnasField.getText().trim());
                
                if (filasIngresadas > 0 && columnasIngresadas > 0) {
                    filas = filasIngresadas;
                    columnas = columnasIngresadas;
                    dialogo.dispose(); 
                    crearCuadricula();
                } else {
                    javax.swing.JOptionPane.showMessageDialog(dialogo, "Los valores deben ser mayores a cero.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(dialogo, "Por favor ingrese numeros enteros validos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        });

        dialogo.add(filasLabel);
        dialogo.add(filasField);
        dialogo.add(columnasLabel);
        dialogo.add(columnasField);
        dialogo.add(confirmarBtn);

        dialogo.setVisible(true);
        
    }//GEN-LAST:event_dimensionesBtnMouseClicked

    private void reporteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteBtnMouseClicked
        try {
            String[] titulos = new String[]{"Token", "Lexema", "Linea", "Columna", "Fila Cuadricula", "Columna Cuadricula", "Color"};
            for (int i = 0; i < tokens.size(); i++) {
                try {
                    datosReporte.add(new String[]{tokens.get(i).getTipo().name(), tokens.get(i).getLexema(), String.valueOf(tokens.get(i).getFilaEditor()), String.valueOf(tokens.get(i).getColumnaEditor()), String.valueOf(casillas.get(i).getFila()), String.valueOf(casillas.get(i).getColumna()), casillas.get(i).getColor()});

                } catch (java.lang.IndexOutOfBoundsException e) {
                    System.out.println("Fuera del limite");
                }
            }
            generarReporte(titulos);
        } catch (NullPointerException e) {
            System.out.println("No hay tokens");
        }
        
    }//GEN-LAST:event_reporteBtnMouseClicked

    private void exportarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exportarBtnMouseClicked
        try {
            // Crear la imagen del panel cuadriculaPanel
            BufferedImage image = new BufferedImage(cuadriculaPanel.getWidth(), cuadriculaPanel.getHeight(), BufferedImage.TYPE_INT_RGB);
            Graphics2D g2d = image.createGraphics();
            cuadriculaPanel.paint(g2d);
            g2d.dispose();

            // Establecer el nombre base del archivo
            String baseName = "cuadricula";
            String extension = ".png";
            String fileName = baseName + extension;
            File file = new File(fileName);

            // Si el archivo ya existe, agregar un sufijo numérico
            int counter = 1;
            while (file.exists()) {
                fileName = baseName + "(" + counter + ")" + extension;
                file = new File(fileName);
                counter++;
            }

            // Guardar la imagen en el archivo
            ImageIO.write(image, "png", file);

            javax.swing.JOptionPane.showMessageDialog(this, "Imagen exportada como " + fileName, "Exportar PNG", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al exportar la imagen: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_exportarBtnMouseClicked

    private void generarReporte(String[] titulos) {
    // Creando la tabla con los titulos y los datos
        String[][] datos = datosReporte.toArray(String[][]::new);
        JTable tabla = new JTable(datos, titulos);

        JScrollPane scrollPane = new JScrollPane(tabla);
        tabla.setFillsViewportHeight(true);

        JDialog dialogo = new JDialog(this, "Reporte", true);
        dialogo.setSize(1000, 600); 
        dialogo.setLocationRelativeTo(this);

        dialogo.add(scrollPane);

        dialogo.setVisible(true);
    }

    
    private void crearCuadricula() {
        cuadriculaPanel.removeAll(); 
        cuadriculaPanel.setLayout(new GridLayout(filas, columnas, 1, 1)); 

        int cellWidth = 500 / columnas;
        int cellHeight = 500 / filas;

        for (int i = 0; i < filas * columnas; i++) {
            JPanel cell = new JPanel();
            cell.setPreferredSize(new Dimension(cellWidth, cellHeight));
            cell.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            cuadriculaPanel.add(cell);
        }

        cuadriculaPanel.revalidate(); 
        cuadriculaPanel.repaint();
        
        this.generarBtn.setEnabled(true);
    }

    private void pintarCuadricula() throws java.lang.IndexOutOfBoundsException{
        if (filas * columnas < colores.size()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Hay mas tokens que cuadros.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

        cuadriculaPanel.removeAll(); 
        
        int cellWidth = 500 / columnas;
        int cellHeight = 500 / filas;
        
        int filaActual = 1;
        int columnaActual = 1;

        // Creando una celda para cada cuadro, asignando un token, fila y columna.
        for (int i = 0; i < filas * columnas; i++) {
            
            if(columnaActual-1 == columnas){
                columnaActual = 1;
                filaActual++;
            }
            
            CuadroPanel celda = new CuadroPanel();
            celda.setPreferredSize(new Dimension(cellWidth, cellHeight));
            try {
                System.out.println("Fila : " + filaActual + " Columna: " + columnaActual);
                celda.setBackground(Color.decode(colores.get(i)));
                celda.setFila(filaActual);
                celda.setColumna(columnaActual);
                celda.setColor(colores.get(i));
                celda.setToken(tokens.get(i));
                casillas.add(celda);
            } catch (IndexOutOfBoundsException e) {
                System.out.println("Cuadricula en blanco");
            }
            
            // Si la fila y columna actual coinciden con los parametros especiales.
            for (int j = 0; j < parametrosEspeciales.size(); j++) {
                if(Integer.parseInt(parametrosEspeciales.get(j)[1]) == filaActual && Integer.parseInt(parametrosEspeciales.get(j)[2]) == columnaActual){
                    celda.setBackground(Color.decode(parametrosEspeciales.get(j)[0]));
                }
            }
            
            columnaActual++;
            
            celda.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            cuadriculaPanel.add(celda);
        }
        
        cuadriculaPanel.revalidate(); 
        cuadriculaPanel.repaint();
        
    }
    
    private void asignarFilasYColumnas(List<Integer> cantidadPalabras){
        for (int i = 0; i < cantidadPalabras.size(); i++) {
            for (int j = 0; j < cantidadPalabras.get(i); j++) {
                matriz.add(new int[]{i+1, j+1});
                System.out.println("Par ordenado: " + (i+1) + " " + (j+1));
            }
        }
        
        for (int i = 0; i < tokens.size(); i++) {
            tokens.get(i).setFilaEditor(matriz.get(i)[0]);
            tokens.get(i).setColumnaEditor(matriz.get(i)[1]);
        }
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cuadriculaPanel;
    private javax.swing.JMenu dimensionesBtn;
    private javax.swing.JMenu exportarBtn;
    private javax.swing.JButton generarBtn;
    private javax.swing.JMenu importarBtn;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu reporteBtn;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
